name: testing-yarn(1477)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os-version }}
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
        os-version: [ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node (${{ matrix.node-version }})
        uses: gowridurgad/setup-node@dummy-token-removal
        # uses: actions/setup-node@v6
        
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn publish
    
