name: testing-pnpm(1477)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os-version }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24]
        os-version: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
            version: 10

      - name: Setup Node (${{ matrix.node-version }}) 
        # uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        uses: ggowridurgad/setup-node@dummy-token-removal
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
        
      - name: pnpm install 
        run: pnpm install
