name: testing_oidc
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v6
    

      - uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        with:
          node-version: '24'
          cache: npm
     



      - run: npm install
        
      - run: npm publish --access public
