name: testing_1477_oidc
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update yarn
        run: yarn set version 3.6.4

      - uses: Satishchoudhary94/setup-node@fix/oidc-support-1440  
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --no-immutable

      - run: yarn publish
