name: testing_1477_oidc

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
        
      - run: |
          echo "===== .npmrc ====="
          cat ~/.npmrc || echo ".npmrc not found"
      - run: npm install -g npm@latest --force  # ensure 11.5.1+
      - run: npm publish --dry-run 
       
