name: testingnpm(1477)

on:
  workflow_dispatch:

jobs:
  no-token-fails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: npm install (this will fail without dummy token)
        run: npm install
        
