name: testing-yarn(1477)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os-version }}
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24]
        os-version: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node (${{ matrix.node-version }})
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: yarn install 
        run: yarn add lodash --dry-run


  node-yarn3-depencies-caching:
    name: Test yarn 3 (Node ${{ matrix.node-version}}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-15-intel]
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v6
      - name: Update yarn
        run: yarn set version 3.6.4
      - name: Yarn version
        run: yarn --version
      # - name: Generate simple .yarnrc.yml
      #   run: |
      #     echo "nodeLinker: node-modules" >> .yarnrc.yml
      # - name: Generate yarn file
      #   run: yarn install
      # - name: Remove dependencies
      #   shell: pwsh
      #   run: Remove-Item node_modules -Force -Recurse
      # - name: Clean global cache
      #   run: yarn cache clean --all
      - name: Setup Node
        uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
    

      
