name: testing-yarn(1477)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        with:
          node-version: '24'

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version
        run: yarn set version stable

      - name: Configure npmjs registry auth
        run: |
          yarn config set npmRegistryServer "https://registry.npmjs.org"
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Publish
        run: yarn npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
