name: testing-pnpm(1477)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6
        with:
            version: 10

      - name: Setup Node
        uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
        
      - run: pnpm publish
        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
